### ISSUE TITLE
AMD issue most likely

### ISSUE THREAD

**Issue by Mineluke1** [notsamicc/FortAlpha#2]
Hey Samicc, I have an issue and I think it might be an AMD issue. If you have something that can fix this, please lmk on discord.

All the heroes (Kyle, Ramierz, Penny, Ninja) are invisible and you can only see their eyes and backbling. (I used Kyle for this screenshot)
Hope you have a fix!

-Mineluke

![unknown (1)](https://user-images.githubusercontent.com/46866718/134740313-e2e9889f-464a-47fc-940e-2e77fc7fa45b.png)

**Comment by voxxid** [comment]
Greetings Mineluke,

fix yo servers

Regards,
voxxid

**Comment by Mineluke1** [comment]
?

**Comment by voxxid** [comment]
Hello Mineluke,

fix yo servers

Regards,
voxxid

**Comment by notsamicc** [comment]
fix yo servers
