### ISSUE TITLE
can you make a tutorial?

### ISSUE THREAD

**Issue by crxshworld** [notsamicc/FortAlpha#6]
i actually didn't understand fully what to do, so i'd be very grateful if you decided to make a tutorial (almost 3 years later lol sry). Thanks!

**Comment by notsamicc** [comment]
sorry mate i don't even have alpha anymore but there's better things out now with tutorials for them like mercury or something

**Comment by crxshworld** [comment]
yeah i figured, i used mercury anyways. Still thanks though! i was
genuinely interested in how all of that mess worked but it’s cool. Hope you
the best, have a good day.
